# Generated by Django 5.0.1 on 2025-08-15 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('IT', 'Information Technology')], max_length=50)),
                ('avatar_url', models.URLField(blank=True, default='https://randomuser.me/api/portraits/men/1.jpg', max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphones', 'Headphones'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('lost', 'Lost/Stolen')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='assets.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('Screen Sign', 'Screen Sign'), ('Paper & Scan', 'Paper & Scan')], default='Screen Sign', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending Scan', 'Pending Scan'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('employee_signature', models.TextField(blank=True)),
                ('it_signature', models.TextField(blank=True)),
                ('employee_acknowledgment', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handovers', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='assets.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_before', models.TextField(blank=True)),
                ('condition_after', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.handover')),
            ],
            options={
                'unique_together': {('handover', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='handover',
            name='assets',
            field=models.ManyToManyField(through='assets.HandoverAsset', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='WelcomePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upn', models.CharField(blank=True, max_length=200)),
                ('auth_method', models.CharField(default='Temporary Access Pass', max_length=50)),
                ('print_welcome_pack', models.BooleanField(default=True)),
                ('print_credential_slip', models.BooleanField(default=True)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('create_teams_chat', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_packs', to='assets.employee')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_welcome_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
