# Generated by Django 5.0.1 on 2025-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcomepack',
            old_name='create_teams_chat',
            new_name='email_sent_to_employee',
        ),
        migrations.RemoveField(
            model_name='welcomepack',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='welcomepack',
            name='print_credential_slip',
        ),
        migrations.RemoveField(
            model_name='welcomepack',
            name='print_welcome_pack',
        ),
        migrations.RemoveField(
            model_name='welcomepack',
            name='send_welcome_email',
        ),
        migrations.RemoveField(
            model_name='welcomepack',
            name='upn',
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='department_info',
            field=models.TextField(blank=True, help_text='Department-specific information'),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='email_sent_to_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='employee_email',
            field=models.EmailField(blank=True, help_text="Employee's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='employee_password',
            field=models.CharField(blank=True, help_text='Temporary password for the employee', max_length=200),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this welcome pack is active'),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='it_contact_person',
            field=models.CharField(blank=True, help_text='Primary IT contact person', max_length=200),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='it_helpdesk_email',
            field=models.EmailField(blank=True, help_text='IT Helpdesk email address', max_length=254),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='it_phone_number',
            field=models.CharField(blank=True, help_text='IT phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='office_location',
            field=models.CharField(blank=True, help_text="Employee's office location", max_length=200),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='start_date',
            field=models.DateField(blank=True, help_text="Employee's start date", null=True),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='teams_email',
            field=models.EmailField(blank=True, help_text="Employee's Teams email", max_length=254),
        ),
        migrations.AddField(
            model_name='welcomepack',
            name='teams_username',
            field=models.CharField(blank=True, help_text="Employee's Teams username", max_length=200),
        ),
    ]
