# Generated by Django 5.0.1 on 2025-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_create_teams_chat_welcomepack_email_sent_to_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='azure_ad_id',
            field=models.CharField(blank=True, help_text='Azure AD Device ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_azure_sync',
            field=models.DateTimeField(blank=True, help_text='Last time data was synced from Azure AD', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='operating_system',
            field=models.CharField(blank=True, help_text='Operating system from Azure AD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, help_text='OS version from Azure AD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='azure_ad_id',
            field=models.CharField(blank=True, help_text='Azure AD User ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='azure_ad_username',
            field=models.CharField(blank=True, help_text='Azure AD User Principal Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID from Azure AD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title from Azure AD', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_azure_sync',
            field=models.DateTimeField(blank=True, help_text='Last time data was synced from Azure AD', null=True),
        ),
    ]
