# Generated by Django 5.0.1 on 2025-08-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_azure_ad_id_asset_last_azure_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
