# Generated by Django 5.0.1 on 2025-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_handover_email_sent_handover_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Pending Scan', 'Pending Scan'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
