# Generated by Django 5.0.1 on 2025-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='license_key',
            field=models.CharField(blank=True, help_text='Software license key', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='license_type',
            field=models.CharField(blank=True, help_text='License type (perpetual, subscription, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Number of seats/licenses', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='subscription_end',
            field=models.DateField(blank=True, help_text='Subscription expiry date', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='used_seats',
            field=models.IntegerField(blank=True, help_text='Number of seats currently in use', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, help_text='Software vendor/developer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='version',
            field=models.CharField(blank=True, help_text='Software version', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headphones', 'Headphones'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('server', 'Server'), ('network_device', 'Network Device'), ('peripheral', 'Peripheral'), ('software_license', 'Software License'), ('subscription', 'Software Subscription'), ('saas', 'SaaS Application'), ('mobile_app', 'Mobile Application'), ('cloud_service', 'Cloud Service'), ('digital_asset', 'Digital Asset'), ('other', 'Other'), ('all', 'All Assets')], max_length=20),
        ),
    ]
