# Generated by Django 5.0.1 on 2025-09-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_license_key_asset_license_type_asset_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Whether this asset can be deleted by non-admin users'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deletion_restricted',
            field=models.BooleanField(default=True, help_text='Whether deletion is restricted to admin users only'),
        ),
    ]
