# Generated by Django 5.0.1 on 2025-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_can_delete_asset_deletion_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintenance_expected_end',
            field=models.DateField(blank=True, help_text='Expected date when maintenance will be completed', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True, help_text='Notes about the maintenance work being performed'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_start_date',
            field=models.DateField(blank=True, help_text='Date when maintenance started', null=True),
        ),
    ]
