# Generated by Django 5.0.1 on 2025-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_maintenance_expected_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
