# Generated by Django 5.0.1 on 2025-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_asset_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='azure_last_signin',
            field=models.DateTimeField(blank=True, help_text='Last sign-in date from Azure AD', null=True),
        ),
    ]
