# Generated by Django 5.0.1 on 2025-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_azure_last_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='health_score',
            field=models.IntegerField(blank=True, help_text='Asset health score (0-100)', null=True),
        ),
    ]
