# Generated by Django 5.0.1 on 2025-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_asset_health_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('console', 'Console (Development)'), ('smtp', 'SMTP Server')], default='console', help_text='Choose the email backend to use', max_length=20)),
                ('from_email', models.EmailField(default='assettrack@harren-group.com', help_text='Email address that will appear as sender', max_length=255)),
                ('from_name', models.CharField(default='AssetTrack System', help_text='Name that will appear as sender', max_length=100)),
                ('smtp_host', models.CharField(default='smtp.office365.com', help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('smtp_username', models.CharField(default='assettrack@harren-group.com', help_text='SMTP username', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption for SMTP')),
                ('company_name', models.CharField(default='Harren Group', help_text='Company name for email branding', max_length=100)),
                ('email_domain', models.CharField(default='harren-group.com', help_text='Domain for email links', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable email sending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
