# Generated by Django 5.0.1 on 2025-10-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_handovertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique token for public access', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether token is active')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times accessed')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('welcome_pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_token', to='assets.welcomepack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
