# Generated by Django 5.0.1 on 2025-10-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_welcomepacktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='health_registration_date',
            field=models.DateTimeField(blank=True, help_text='Date when health score was calculated and registered', null=True),
        ),
    ]
