# Generated by Django 5.0.1 on 2025-10-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_asset_health_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='health_registration_date',
        ),
    ]
