# Generated by Django 5.0.1 on 2025-10-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_add_azure_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='azure_registration_date',
            field=models.DateTimeField(blank=True, help_text='Date when device was registered in Azure AD', null=True),
        ),
    ]
