# Generated by Django 5.0.1 on 2025-10-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_add_azure_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('extern', 'External')], default='active', help_text='Employee status from Azure AD sync', max_length=20),
        ),
    ]
