# Generated by Django 5.0.1 on 2025-10-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('IT', 'Information Technology'), ('External', 'External')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', help_text='Employee status from Azure AD sync', max_length=20),
        ),
    ]
