# Generated by Django 5.0.1 on 2025-10-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_asset_office_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='office_location',
        ),
    ]
