# Generated by Django 5.0.1 on 2025-10-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_remove_asset_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='office_location',
            field=models.CharField(choices=[('bernem', 'Bernem Office'), ('hamburg', 'Hamburg Office'), ('other', 'Other Location')], default='bernem', help_text='Office location where the asset is located', max_length=20),
        ),
    ]
