# Generated by Django 5.0.1 on 2025-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_asset_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_location',
            field=models.CharField(choices=[('bernem', 'Bernem Office'), ('hamburg', 'Hamburg Office'), ('other', 'Other Location')], default='bernem', help_text='Office location where the employee is based', max_length=20),
        ),
    ]
