# Generated by Django 5.0.1 on 2025-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_alter_employee_department_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='st_tag',
            field=models.CharField(blank=True, help_text='ST tag for asset identification', max_length=50, null=True),
        ),
    ]
