# Generated by Django 5.0.1 on 2025-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_add_st_tag_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office_location',
            field=models.CharField(choices=[('bermen', 'Bremen Office'), ('hamburg', 'Hamburg Office'), ('other', 'Other Location')], default='bermen', help_text='Office location where the asset is located', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_location',
            field=models.CharField(choices=[('bermen', 'Bremen Office'), ('hamburg', 'Hamburg Office'), ('other', 'Other Location')], default='bermen', help_text='Office location where the employee is based', max_length=20),
        ),
    ]
