version: "3.9"
services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=assettrack_django.settings_production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
